### ISSUE TITLE
"CrtException: Could not detect a supported platform" in Android and iOS Unity apps

### ISSUE THREAD

**Issue by ivgnt** [awslabs/aws-crt-dotnet#90]
Some time ago we had an issue with SigV4A signing which was fixed by the AWS team: aws/aws-sdk-net#2126

Everything worked fine while we were testing on windows, but now we see this error when building and installing the app on both Android and iOS devices

> CrtException: Could not detect a supported platform
> at Aws.Crt.Platform.GetRuntimePlatformOS () [0x00000] in <00000000000000000000000000000000>:0
> at Aws.Crt.CRT+PlatformBinding..ctor () [0x00000] in <00000000000000000000000000000000>:0
> at Aws.Crt.CRT..cctor () [0x00000] in <00000000000000000000000000000000>:0
> at Aws.Crt.NativeAPI..cctor () [0x00000] in <00000000000000000000000000000000>:0
> at Aws.Crt.Auth.AwsSigner+API..cctor () [0x00000] in <00000000000000000000000000000000>:0
> at Aws.Crt.Auth.AwsSigner.SignHttpRequest (Aws.Crt.Http.HttpRequest request, Aws.Crt.Auth.AwsSigningConfig signingConfig) [0x00000] in <00000000000000000000000000000000>:0
> at Amazon.Extensions.CrtIntegration.CrtAWS4aSigner.SignRequest (Amazon.Runtime.Internal.IRequest request, Amazon.Runtime.IClientConfig clientConfig, Amazon.Runtime.Internal.Util.RequestMetrics metrics, Amazon.Runtime.ImmutableCredentials credentials) [0x00000] in <00000000000000000000000000000000>:0
> at Amazon.Runtime.Internal.Auth.S3Signer.Sign

**Comment by DmitriyMusatkin** [comment]
We currently dont support CRT dotnet bindings on Android or IOS. We started internal discussion on when we can support those platforms. I'll update the ticket once i have more info.

**Comment by NikitaMironenkoUrmobi** [comment]
any updates?

**Comment by genifycom** [comment]
I too would like to know the status. This issue currently precludes me from using CloudFront KeyValueStore in Android which is a valuable caching strategy.

**Comment by bretambrose** [comment]
Android support is provided by aws-crt-java.  There are no current plans to extend it to aws-crt-dotnet.
